# Default values for plugin-center-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: scmmanager/plugin-center-api
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: plugin-center-api.scm-manager.org
      paths:
        - /api

  tls:
    - secretName: plugin-center-api-tls-secret
      hosts:
        - plugin-center-api.scm-manager.org

resources:
  limits:
    memory: 20Mi
  requests:
    cpu: 100m
    memory: 20Mi

nodeSelector: {}

tolerations: []

affinity: {}
